app_blog:
    path: /blog
    controller: App\Controller\BlogController::index
app_feed:
    path: /feed
    controller: App\Controller\BlogController::feed
app_event:
    path: /event
    controller: App\Controller\EventController::index
vos_evenements:
    path: /vos-evenements
    controller: 'App\Controller\EventController::vosEvenements'
app_login:
    path: /login
    controller: 'App\Controller\LoginController::login'
evenements_delete:
    path: /evenements/{id}
    controller: 'App\Controller\EventController::deleteEvent'
    methods: ['POST']
evenements_index:
    path: /evenements
    controller: 'App\Controller\EventController::index'
    methods: ['GET']
event_participate:
    path: /evenement/participate/{eventId}
    controller: App\Controller\EventController::participate
    methods: ['POST']
app_admin:
    path: /admin
    controller: App\Controller\AdminController::index
app_admin_users:
    path: /admin/users
    controller: App\Controller\AdminController::getAllUsers
app_admin_posts:
    path: /admin/posts
    controller: App\Controller\AdminController::getAllPosts
app_admin_groups:
    path: /admin/groups
    controller: App\Controller\AdminController::getAllGroups
app_admin_events:
    path: /admin/events
    controller: App\Controller\AdminController::getAllEvents
app_admin_products:
    path: /admin/produits
    controller: App\Controller\AdminController::getAllProducts
app_admin_reports:
    path: /admin/reports
    controller: App\Controller\AdminController::getAllReports
evenements_delete_admin:
    path: /evenements-admin/{id}
    controller: 'App\Controller\AdminController::deleteEventAdmin'
    methods: ['POST']
events_this_week:
    path: /eventsThisWeek
    controller: App\Controller\EventController::eventsThisWeek