app_blog:
    path: /blog
    controller: App\Controller\BlogController::index
app_feed:
    path: /feed
    controller: App\Controller\BlogController::feed
add_like:
    path: /add-like/{id}
    controller: App\Controller\PublicationsController::addLike