# config/services.yaml
parameters:
    images_directory: '%kernel.project_dir%/public/images/'
    forbidden_words:
        - badword1
        - badword2
        - badword3
    locale: 'fr_FR'  # Set the default locale value here

services:        
    # Default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    # Makes classes in src/ available to be used as services
    # This creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Add more service definitions when explicit configuration is needed
    # Please note that last definitions always *replace* previous ones

    # Register the Twig extension as a service
    App\Twig\AppExtension:
        tags: ['twig.extension']  # This tag registers the class as a Twig extension
    App\Services\CountryApi:
        arguments:
            $apiUrl: 'https://restcountries.com/v3.1/all?fields=name'

    App\Notifier\MyNotifier:

    # Define the BadWordsService as a service
    App\Services\BadWordsService:
        # Inject the path to the JSON file containing bad words
        arguments:
            $badWordsFilePath: '%kernel.project_dir%/config/bad_words.json'

    # Define the MailgunEmailService as a service
    App\Services\MailgunEmailService:
        arguments:
            $domain: '%mailgun.domain%'
    
    Facebook\Facebook:
        arguments:
            $config: 
                'app_id': '%env(FACEBOOK_APP_ID)%'
                'app_secret': '%env(FACEBOOK_APP_SECRET)%'
                'default_graph_version': 'v12.0'